### ISSUE TITLE
iOS app killed - Click on notification not open specific screen

### ISSUE THREAD

**Issue by vavdiyaharesh** [pushy/pushy-flutter#49]
when ios app is closed(not open even in recent) clicking on notification not getting triggered. for android works well and for ios when app is open also work.

**Comment by pushy** [comment]
Hi @vavdiyaharesh,
Thanks so much for reporting this issue.

We've resolved the crash in https://github.com/pushy/pushy-flutter/commit/57e2a56183f0a99a033c4dd0ed946cac3ca30faf and published version `2.0.11` of the Pushy Flutter SDK.

1) Please update the [Pushy Flutter SDK](https://pushy.me/docs/additional-platforms/flutter) in your app by editing the `pubspec.yaml` in the root directory of your project and updating the `pushy_flutter` package version to `2.0.11`:
```
pushy_flutter: 2.0.11
```

2) Run `flutter pub get` to fetch the new version of our SDK.

That being said, manually relaunching killed Flutter iOS apps built in Debug mode on iOS 14+ devices is [not officially supported](https://github.com/flutter/flutter/issues/66422#issuecomment-697972897). Therefore, while your app will no longer crash, you won't be able to test the notification click handler functionality with your app swiped away if you build it in debug mode.

To test this functionality, please build and deploy your app in Release mode by running:

```
flutter run --release
```

You will then be able to relaunch your killed app without any issues, including from an incoming push notification.

Please let us know if you face any issues.
