### ISSUE TITLE
Android Notification

### ISSUE THREAD

**Issue by rwaidKalka** [pushy/pushy-flutter#53]
Android notification is not receiving when app is closed

**Comment by pushy** [comment]
Hi @rwaidKalka,
Thanks for reaching out. We'd be glad to assist.

Please refer to the following article in our support center for help on this topic:
[How can I send notifications to Android devices in Doze / power saving mode?](https://support.pushy.me/hc/en-us/articles/360043423332)

**Comment by rwaidKalka** [comment]
Thanks for your instructions i already did that one too i disabled the battery optimization and still the notification is not reached to us while the app is terminated
is there anything else i can try to solve this issue ?
i am using flutter framework for the app development and the ios doesn't have any issue only android has this issue.

**Comment by pushy** [comment]
Hi @rwaidKalka,
I'd be glad to help you investigate this issue further.

If you could please provide the following information about a device experiencing this issue, that would be great:

1) Device manufacturer
2) Device model name
3) Android OS version

**Comment by pushy** [comment]
Hi @rwaidKalka,
Can you please share your project's `main.dart`? You may also send it to us privately at support@pushy.me.

**Comment by rwaidKalka** [comment]
Sure i am gonna send it right now but i did the configuration in another file which is app.dart i will send both of them from the main.dart i called tha app.dart file in the runApp.

**Comment by rwaidKalka** [comment]
Hello
I already sent the code to the provided email but i didn't receive any
email.

**Comment by pushy** [comment]
Hi @rwaidKalka,
Thanks for sending over your code.

You're experiencing this behavior because your `backgroundNotificationListener` is inside `app.dart` instead of being inside `main.dart`. 

As per the [Flutter docs](https://pushy.me/docs/additional-platforms/flutter), please ensure the following method is inside your `main.dart` file (remove it from `app.dart`), right after the `import` statements, and outside any `Widget` class declaration, to process push notifications in the background via a Flutter background isolate:

```
// Please place this code in main.dart,
// After the import statements, and outside any Widget class (top-level)

@pragma('vm:entry-point')
void backgroundNotificationListener(Map<String, dynamic> data) {
    // Print notification payload data
    print('Received notification: $data');

    // Notification title
    String notificationTitle = 'MyApp';

    // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
    String notificationText = data['message'] ?? 'Hello World!';

    // Android: Displays a system notification
    // iOS: Displays an alert dialog
    Pushy.notify(notificationTitle, notificationText, data);

    // Clear iOS app badge number
    Pushy.clearBadge();
}
```

**Comment by bawahakim** [comment]
For future readers, it seems I was able to setup the entry point as a static method in an arbitrary class:

```
class MyClass {
  @pragma('vm:entry-point')
  static void _backgroundNotificationListener(Map<String, dynamic> data) {
    ...
   }
  void init() {
      Pushy.listen();
      Pushy.setNotificationListener(_backgroundNotificationListener);
      ...
  }
}
```

Seems flutter documentation allows it, and the package `awesome_notifications` does it this way too
https://pub.dev/documentation/flutter_isolate/latest/
