### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by stephane-segning** [pushy/pushy-flutter#54]
Hello, thank you for this lib. I'm implementing a cross-platform app like we use to do with Flutter. Actually the plugin do work fine on android and ios. Only. But not on web. So my question is to understand how we could add web support for that. I saw there's already a [sdk for web](https://github.com/pushy/pushy-sdk-web) so the integration could be fast. What do you recommend?

**Comment by pushy** [comment]
Hi @stephane-segning,
Thanks for reaching out. We'd be glad to assist.

We've just released version `2.0.17` of `pushy_flutter` which adds support for the Flutter Web platform using the [Pushy Web SDK](https://pushy.me/docs/web-push/get-sdk).

1) Please edit the `pubspec.yaml` in the root directory of your project and update the plugin version referenced to the following:

```
pushy_flutter: 2.0.17
```

2) Run `flutter pub get` to fetch the new version.

3) Follow the [Flutter Web integration instructions](https://pushy.me/docs/additional-platforms/flutter#:~:text=Add%20Support%20for%20Flutter%20Web).

4) Run your app and observe whether the Web Push SDK is able to register for and receive push notifications.

Please let us know if you face any issues, or have any questions.
