### ISSUE TITLE
Dialog pop in IOS when app is in foreground.

### ISSUE THREAD

**Issue by faizanShoukat55** [pushy/pushy-flutter#55]
Hy Pushy!
I want to remove the dialog when a notification occurs in the foreground and at the same time notification disappears from the notification list it should remain there. Just want to remove the extra dialog.
Hope for the best.

**Comment by pushy** [comment]
Hi @faizanShoukat55,
We'd be glad to assist.

To remove the popup alert on iOS when a notification is received, please find this line of code in your `lib/main.dart`:
```
Pushy.notify(notificationTitle, notificationText, data);
```

Replace it with the following:
```
// Only call Pushy.notify() on Android
if (Platform.isAndroid) {
    Pushy.notify(notificationTitle, notificationText, data);
}
```

Please let us know if you have any further questions or face any issues.

**Comment by faizanShoukat55** [comment]
Hi @pushy 
Thank you its working perfect
