### ISSUE TITLE
Infinix Mobile Notification Issue

### ISSUE THREAD

**Issue by faizanShoukat55** [pushy/pushy-flutter#56]
Hi @pushy 
I am facing issues with notifications. It's working perfectly in Samsung while sending to Infinix Mobiles, the notification does not appear.
What should I do now?

Best Regards
Faizan Shoukat

**Comment by pushy** [comment]
Hi @faizanShoukat55,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Please consult this article for a solution:
https://support.pushy.me/hc/en-us/articles/360043864791

Please let me know if there's anything else we can help with.
