### ISSUE TITLE
Crashes and Freezes Pushy.Register() on VIVO and OPPO devices .

### ISSUE THREAD

**Issue by farahfarah1** [pushy/pushy-flutter#57]
Fatal Exception: java.lang.IllegalArgumentException
com.youtap.indo.merchant: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by pushy** [comment]
Hi @farahfarah1,
Thanks for reaching out. We'd be glad to assist.

Our SDK already declares the `FLAG_IMMUTABLE` flag when creating a `PendingIntent` in the latest versions of the SDK:
https://github.com/pushy/pushy-flutter/blob/6aba3c86dac0b78d37b44349f08535b21e3486d6/android/src/main/java/me/pushy/sdk/flutter/util/PushyNotification.java#L56

Please ensure you are using the latest version of the Pushy Flutter SDK.

Install version `2.0.18` of our [Flutter SDK](https://pub.dev/packages/pushy_flutter) by editing the `pubspec.yaml` in the root directory of your project and specifying the following under the dependencies section:
```
pushy_flutter: 2.0.18
```

Run `flutter pub get` to fetch the dependency.

Please let us know if this resolves your issue, or if you require any further assistance.
