### ISSUE TITLE
Status Bar Notification Issue In Android

### ISSUE THREAD

**Issue by faizanShoukat55** [pushy/pushy-flutter#58]
Hy Pushy
Notification icon not showing properly in status bar in release mode while its working perfect in debug mode.
Its showing black  icon in dark mode.
Please check it.

**Comment by pushy** [comment]
Hi @faizanShoukat55,
Thanks for reaching out. We'd be glad to assist.

On Android 6.0 Lollipop and up, notification icons cannot contain any color channels. The notification icon you use must be transparent, with only an alpha channel, and have no background color. You can convert your `.png` to a valid notification icon by [using this third-party tool](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.space.trim=1&source.space.pad=0&name=ic_stat_example
).

Please let us know if you require any further assistance.

**Comment by faizanShoukat55** [comment]
Hi @pushy yes I am using the grey Scale Icon. But the issue is still the same.
Even tried to use your sample project icon "ic_notify" in my own project but the response is still the same.
It works perfectly in debug mode while in release mode icon goes grey out.
Please help me out in this regard. 
![ic_notification_logo_grayscale](https://github.com/pushy/pushy-flutter/assets/37035175/cf526d08-5c69-4414-a4b3-96d6f3c92b4a)

**Comment by pushy** [comment]
Hi @faizanShoukat55,
Please try the solution mentioned here:
https://stackoverflow.com/a/61303224/1123355
