### ISSUE TITLE
Feature: Support for Linux

### ISSUE THREAD

**Issue by akshaybabloo** [pushy/pushy-flutter#59]
Are there any plans of adding Linux support?

I am building an IoT application that requires a notification prompts to do some tasks.

**Comment by pushy** [comment]
Hi @akshaybabloo,
Thanks for reaching out. We'd be glad to assist.

Unfortunately, there are no current plans to add Linux support for receiving notifications. Notifications can only be sent from Linux using the [Send Notifications API](https://pushy.me/docs/api/send-notifications), but not received.

We apologize for the inconvenience.
