### ISSUE TITLE
Pushy.register get device token giving error

### ISSUE THREAD

**Issue by agilst** [pushy/pushy-flutter#60]
I have followed all the instructions but got this error when calling `Pushy.register()`:
`PlatformException(PUSHY ERROR, Error("This feature is temporarily unavailable. Please contact us ...`

Did I miss something on my configuration?

**Comment by pushy** [comment]
Hi @agilst,
The issue is caused because your account is suspended due to a billing issue.

Please log in to our [dashboard](https://dashboard.pushy.me) and update your card on file and it will be resolved.
