### ISSUE TITLE
Android , Pushy ( 7552): Notifications have been disabled by the app

### ISSUE THREAD

**Issue by abbasjaber** [pushy/pushy-flutter#63]
Hello, I'm facing this issue with Android devices I tried with three different devices and Android OS.
`Pushy ( 7552): Notifications have been disabled by the app`
I followed the documentation to implement Pushy for my Flutter app.
I'm using topics to register users.

**Comment by pushy** [comment]
Hi @abbasjaber,
Thanks for reaching out. We'd be glad to assist.

"Notifications have been disabled by the app" means that your app has called the `Pushy.toggleNotifications(false)` method. To re-enable notifications, simply pass `true` into this method as follows:

```
Pushy.toggleNotifications(true);
```

If you do not wish for the device to ever stop receiving notifications, please remove all invocations of `Pushy.toggleNotifications(false);` from your app.

Please give it a try, and let us know if you face any issues.

**Comment by abbasjaber** [comment]
Thanks yes this solved my issue
