### ISSUE TITLE
await Pushy.register()

### ISSUE THREAD

**Issue by LucasLau00** [pushy/pushy-flutter#65]
For the main.dart file, I have it copied from the pub.dev at the example all code is working fine until the part which calls the await Pushy.register(), it does not proceed to do anything it just gets stuck. Nothing is returned on my side of console. I have also added loggign statements before and after it, the before one is called and the one after is not executed which means that it is stuck at this part.

**Comment by LucasLau00** [comment]
Just testing with the https://github.com/pushy/pushy-demo-flutter/tree/master and still not working
on Android studio Iguana 2023.2.1 Patch 1
XCODE 15.3
IOS Simulator 17.4
Flutter SDK 3.19.3
MACOS: Sonoma
Pushy tested with both .18 and .17 both hangs and didn't return anything.
It is using your code only so no other services are used for now. Disabled swizzling as well.
Have also set my own bundle identifier and selected my own development team in Xcode.

**Comment by pushy** [comment]
Hi @LucasLau00,
Thanks for reporting this issue. We'd be glad to assist.

The issue most likely stems from the use of the iOS Simulator, can you please try with a physical iOS device to see whether you can reproduce the issue?

**Comment by pushy** [comment]
Hi @LucasLau00,
Thanks for reporting this issue. We'd be glad to assist.

The issue most likely stems from the use of the iOS Simulator, can you please try with a physical iOS device to see whether you can reproduce the issue?

Also, what do you mean by "disabled swizzling"? Please do not disable swizzling, it should not be disabled unless you need to include other APNs-dependent SDKs such as Firebase Auth, Firebase Messaging, OneSignal, etc. Disabling swizzling will actually lead to a hanging `Pushy.register()` call.

**Comment by LucasLau00** [comment]
Yes tested on my physical device with the demo. Device is ios17.3.1 iphone15 pro. Connected via type c to c and executed with android studio.

**Comment by LucasLau00** [comment]
> Hi @LucasLau00,
> 
> Thanks for reporting this issue. We'd be glad to assist.
> 
> 
> 
> The issue most likely stems from the use of the iOS Simulator, can you please try with a physical iOS device to see whether you can reproduce the issue?
> 
> 
> 
> Also, what do you mean by "disabled swizzling"? Please do not disable swizzling, it should not be disabled unless you need to include other APNs-dependent SDKs such as Firebase Auth, Firebase Messaging, OneSignal, etc. Disabling swizzling will actually lead to a hanging `Pushy.register()` call.

Thanks for the reply will remove it and give it a try and let you know the outcome thank you.

**Comment by pushy** [comment]
Hi @LucasLau00,
Please do not remove the invocation of `pushy.toggleMethodSwizzling(false)`, please instead replace it with the following:

```
pushy.toggleMethodSwizzling(true);
```

**Comment by LucasLau00** [comment]
After doing `pushy.toggleMethodSwizzling(true);` it managed to work on real device but still not working on IOS Simulators. Thanks for the advice, if there are any ways simulators can be made to work it would be great thanks in advance.

**Comment by pushy** [comment]
Hi @LucasLau00,
Are you using an M1, M2, or T2 Mac?

As per Apple specifications, only Apple Silicon M1, M2, and T2 Macs can register for and receive push notifications via APNs in the iOS Simulator.

**Comment by pushy** [comment]
Closing due to lack of response, please feel free to let us know if you're still facing this issue.

**Comment by agilst** [comment]
@pushy I am using Mac M1, `pushy_flutter: 2.0.28`, and set the `Pushy.toggleMethodSwizzling(true)` but still stuck at running `await Pushy.register()`. any suggestions?
```
Future<void> initPushy() async {
    Pushy.listen();
    Pushy.toggleFCM(true);
    Pushy.toggleMethodSwizzling(true);
    Pushy.toggleInAppBanner(true);

    try {
      Log.d('get token', label: 'pushy');
      String deviceToken = await Pushy.register(); // hangs at this line
      UserSessionManager.setPushyDeviceToken(deviceToken);
      Log.d(deviceToken, label: 'pushy token');
    } on PlatformException catch (error) {
      Log.e(error.message, label: 'pushy');
    }
    
    Pushy.setNotificationListener(backgroundNotificationListener);
    Pushy.setNotificationClickListener((Map<String, dynamic> data) {
      Log.d(data, label: 'pushy clicked');
      Pushy.clearBadge();
    });
  }
```
