### ISSUE TITLE
Unable to send notification on deivce id in flutter

### ISSUE THREAD

**Issue by AbhayProgrammer** [pushy/pushy-flutter#66]
No devices matched the specified condition. Please double-check the device token(s) or Pub/Sub topic(s), and that you are authenticating using a Secret API Key assigned to the Pushy app of the recipient device(s)

Getting this in IOS only when sending notification also i am using swizzling method with fcm notification
I need both in my app to be worked.
Please tell me how can i rid of this problem

Thanks you

**Comment by pushy** [comment]
Hi @AbhayProgrammer,
Thanks for reaching out. We'd be glad to assist.

Please ensure you have created an app in the [Pushy dashboard](https://dashboard.pushy.me/) with the same iOS Bundle ID as you configured in your Xcode project:

![identifier](https://github.com/pushy/pushy-flutter/assets/13287630/4b63291a-14fc-437c-b840-5e290302256c)

This will ensure that the device registrations get associated with your own Pushy dashboard app, and you'll then be able to send notifications by specifying that Pushy dashboard app's Secret API Key, which is available in the API Authentication tab.
