### ISSUE TITLE
Registration failed: The application identifier is missing

### ISSUE THREAD

**Issue by nj9666-xcelore** [pushy/pushy-flutter#69]
I'm getting this issue but I flowed all steps that you are mentioned in official documentation.   

Device token error: PlatformException(PUSHY ERROR, Registration failed: The application identifier is missing. Are you using ProGuard? Please contact support., null, null)

please let me know if I have to additionally add something except from Doc

**Comment by pushy** [comment]
Hi @nj9666-xcelore,
Thanks for reaching out. We'd be glad to assist.

Flutter comes preconfigured with ProGuard. Please make sure the following lines are present in your project's `android/app/proguard-rules.pro` file (please create this file if it doesn't exist yet):

```
-dontwarn me.pushy.**
-keep class me.pushy.** { *; }
-keep class androidx.core.app.** { *; }
-keep class android.support.v4.app.** { *; }
```

Please give it a try, and let us know if you need any further assistance.
