### ISSUE TITLE
Namespace is missing 

### ISSUE THREAD

**Issue by farahfarah1** [pushy/pushy-flutter#70]
com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/builder/.pub-cache/hosted/pub.dev/pushy_flutter-2.0.20/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by pushy** [comment]
Hi @farahfarah1 ,
Thanks so much for reporting this issue, and for submitting a PR!

We've merged your PR and published version `2.0.21` to [pub.dev](https://pub.dev/packages/pushy_flutter).

1) Please update the [Pushy Flutter SDK](https://pushy.me/docs/additional-platforms/flutter) in your app by editing the `pubspec.yaml` in the root directory of your project and updating the `pushy_flutter` package version to `2.0.21`:
```
pushy_flutter: 2.0.21
```

2) Run `flutter pub get` to fetch the new version of our SDK.

Please let us know if there's anything else we can help with.
