### ISSUE TITLE
iOS app not receiving heads up notification when app is in the foreground

### ISSUE THREAD

**Issue by justatipfromthedeadsequoiatree** [pushy/pushy-flutter#73]
does Pushy provide heads up notification for iOS devices when app is in foreground?

**Comment by pushy** [comment]
Hi @justatipfromthedeadsequoiatree ,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Yes, the Pushy Flutter SDK supports in-app notification banners on iOS 10+.

Please ensure your app is calling the following method before `Pushy.setNotificationListener()` for in-app banners to be displayed:

```
// Enable in-app notification banners (iOS 10+)
Pushy.toggleInAppBanner(true);
```

Please let us know if there's anything else we can help with.
