### ISSUE TITLE
 GetX with pushy problem

### ISSUE THREAD

**Issue by ahmad22aot** [pushy/pushy-flutter#74]
because pushy_flutter >=2.0.17 depends on get ^4.6.5 and direct_serivce depends on get ^5.0.0-release-candidate-6, pushy_flutter >=2.0.17 is forbidden.
So, because direct_serivce depends on pushy_flutter ^2.0.22, version solving failed.

**Comment by pushy** [comment]
Hi @ahmad22aot ,
Thanks for reaching out. We'd be glad to assist with your inquiry.

We could not find any package called [`direct_serivce`](https://pub.dev/packages/direct_serivce) on `pub.dev`. Is this your Flutter project name? If so, you can fix the issue by downgrading your `get` package in `pubspec.yaml` file to `^4.6.5`.

Then, run `flutter pub get` to resolve the issue.

Please let us know if there's anything else we can help with.

**Comment by ahmad22aot** [comment]
**direct_serivce** is app package name
It's not logical to use Getx to determine the platform type, thereby forcing users to use the same version. There are many ways to determine the platform type. Please resolve this issue

**Comment by pushy** [comment]
Hi @ahmad22aot,
Thanks for clarifying

We've just published version `2.0.23` of the Pushy Flutter SDK which removes the GetX dependency and instead relies on `Platform` and `kIsWeb` instead for detecting the running platform. 

Install version `2.0.23` of our [Flutter SDK](https://pub.dev/packages/pushy_flutter) by editing the `pubspec.yaml` in the root directory of your project and changing the version in the dependencies section:

```
pushy_flutter: 2.0.23
```

Run `flutter pub get` to fetch the updated dependency.
