### ISSUE TITLE
Pushy-Flutter: Background Notifications Not Working When App is Killed

### ISSUE THREAD

**Issue by aungaung001** [pushy/pushy-flutter#78]
Description:

When using `pushy_flutter` version `2.0.24`, background notifications are not received when the app is killed. This issue occurs due to the limitations of Flutter’s background execution, particularly with the use of `SharedPreferences` for storing user settings.

Steps to Reproduce:
1. Configure `Pushy` in the Flutter app.
2. Implement `backgroundNotificationListener` with `SharedPreferences`.
3. Send a background notification while the app is in the killed state.

Expected Behavior:
The notification should be displayed even if the app is killed, based on the schedule stored in `SharedPreferences`.

Actual Behavior:
Notifications are not displayed when the app is killed.

Possible Cause:
`SharedPreferences` might not be accessible in a background isolate when the app is completely terminated.

Environment:
- Pushy-Flutter Version: 2.0.24
- Flutter Version: (e.g., 3.3.2)
- Device: (e.g., Xiaomi MI 5X, Android 9)
- SharedPreferences Version: Latest
- Android SDK: (e.g., 29)

Code Snippet:
`@pragma('vm:entry-point')
static Future<void> backgroundNotificationListener(Map<String, dynamic> data) async {
  SharedPreferences shared = await SharedPreferences.getInstance();
  List<String>? jsonList = shared.getStringList("user_schedule");
  // Notification logic based on user_schedule
}`

What can i do for this issues?
Is there any solution for this?

**Comment by pushy** [comment]
Hi @aungaung001,
Thanks for reaching out. We'd be glad to assist.

It appears to be a bug in `SharedPreferences` which can be solved by calling `reload()` as follows:

```
SharedPreferences shared = await SharedPreferences.getInstance();
shared.reload();  // The magic line 
```

Try adding this line of code to your app and let us know whether it resolves the issue.

**Comment by aungaung001** [comment]
Thanks it is working now
