### ISSUE TITLE
Request for Assistance with Refresh API Call on Receiving Notification

### ISSUE THREAD

**Issue by aungaung001** [pushy/pushy-flutter#79]
Dear Pushy Support Team,

I am currently using the `pushy_flutter` package (version 2.0.24) in my Flutter project and need assistance with implementing a refresh API call upon receiving a notification **when the user is actively using the application**. Specifically, I want to trigger an API call automatically every time a new push notification is received to update my app’s content in real-time when the app is in the foreground.

Please guide me on how to integrate this functionality effectively. Is there a recommended way to listen for incoming notifications and perform an API call within the `onMessageReceived` handler only when the user is actively using the app? Any example code or documentation would be greatly appreciated.

I appreciate your support!

**Comment by pushy** [comment]
Hi @aungaung001,
Thanks for reaching out. We'd be glad to assist with your inquiry.

Please note that your `backgroundNotificationListener` will also be invoked when the app is running in the foreground.

Therefore, you simply have to add the following code inside your `main.dart` to track the app foreground state and act accordingly:

```
  // Add this above the backgroundNotificationListener() declaration
  bool _isInForeground = false;

  // Add this code inside your Widget initState() in main.dart:
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance!.addObserver(this);
  }
  
  // Add these method overrides to your Widget in main.dart:
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    _isInForeground = state == AppLifecycleState.resumed;
  }

  @override
  void dispose() {
    WidgetsBinding.instance!.removeObserver(this);
    super.dispose();
  }
```

You may now check the value of `_isInForeground` inside your `backgroundNotificationListener` and fetch data from a remote API in case it is `true`.

Please give it a try, and let us know if you face any issues.
