### ISSUE TITLE
Adding Timestamp in Notification 

### ISSUE THREAD

**Issue by aungaung001** [pushy/pushy-flutter#82]
i want pushy noti with time stamp
like this 
 
How can i add in followin code 
  Pushy.notify(title, description, data);

![1810d33be685cd8a90f64c98b7b83e283a4b300d_2_690x197](https://github.com/user-attachments/assets/a0a75759-2021-4369-b61d-b7bc4c988c37)

**Comment by pushy** [comment]
Hi @aungaung001,
Thanks for reaching out. We'd be glad to assist with your inquiry.

On Android, notifications issued by `Pushy.notify()` already automatically display the time / timestamp next to your app name:

![image](https://github.com/pushy/pushy-demo-flutter/blob/master/assets/screenshots/4.png?raw=true)

Please let us know if there's anything else we can help with.
