### ISSUE TITLE
[2.0.28] await Pushy.register() hangs on iPhone physical device

### ISSUE THREAD

**Issue by agilst** [pushy/pushy-flutter#83]
@pushy I am using Mac M1, iPhone SE 2020 registered on Apple dev account, `pushy_flutter: 2.0.28`, and set the `Pushy.toggleMethodSwizzling(true)` but still stuck at running `await Pushy.register()` by following this solution #65. any suggestions?
```
Future<void> initPushy() async {
    Pushy.listen();
    Pushy.toggleFCM(true);
    Pushy.toggleMethodSwizzling(true);
    Pushy.toggleInAppBanner(true);

    try {
      Log.d('get token', label: 'pushy');
      String deviceToken = await Pushy.register(); // hangs at this line
      UserSessionManager.setPushyDeviceToken(deviceToken);
      Log.d(deviceToken, label: 'pushy token');
    } on PlatformException catch (error) {
      Log.e(error.message, label: 'pushy');
    }
    
    Pushy.setNotificationListener(backgroundNotificationListener);
    Pushy.setNotificationClickListener((Map<String, dynamic> data) {
      Log.d(data, label: 'pushy clicked');
      Pushy.clearBadge();
    });
  }
```

**Comment by pushy** [comment]
Hi @agilst,
Thanks for reaching out. We'd be glad to assist with your inquiry.

If the `Pushy.register()` callback isn't invoked in your iOS app, please ensure your project isn't using any other push notification library, such as Firebase Cloud Messaging, Firebase Auth, APNs, OneSignal, React Native Push Notification, etc.

These libraries clash with the Pushy iOS SDK as they hook into (swizzle) the APNs methods which the Pushy iOS SDK relies on.

Also, please make sure your `AppDelegate class` does not override any of the following APNs methods:

```
application:didRegisterForRemoteNotificationsWithDeviceToken
application:didFailToRegisterForRemoteNotificationsWithError
application:didReceiveRemoteNotification:fetchCompletionHandler
```

If you'd like to use multiple push libraries at the same time, please see [this article](https://support.pushy.me/hc/en-us/articles/360053017131) to disable swizzling in the Pushy iOS SDK while invoking our internal methods manually in each AppDelegate APNs callback.

Please let us know if there's anything else we can help with.

**Comment by agilst** [comment]
Mark this as resloved by following above article.
