### ISSUE TITLE
Pushy notifications not showing when app is killed or inactive

### ISSUE THREAD

**Issue by xanderelsmith** [pushy/pushy-flutter#84]
Currently trying to implement notifications , need it to show in background, even when user is not on the app. 

Flutter version: 3.24.0
Pushy version: 2.0.28

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:parse_server_sdk_flutter/parse_server_sdk_flutter.dart';
import 'package:spark_ai/internals/api_private_keys.dart';
import 'package:spark_ai/internals/localstorage/hivedb_functions.dart';
import 'package:spark_ai/services/api_services.dart';
import 'package:spark_ai/styles/themes.dart';
import 'internals/routes.dart';
import 'package:pushy_flutter/pushy_flutter.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();
  await hivedbEndPoint();

  if (!kIsWeb) {
    MobileAds.instance.initialize();
  }

  await Parse().initialize(
      appName: 'Spark',
      appVersion: '1.0',
      ApiPrivateKeys.kappId,
      ApiPrivateKeys.keyParseServerUrl,
      clientKey: ApiPrivateKeys.kclientKey,
      debug: true,
      autoSendSessionId: true);

// SDK is initialized, start loading ads
  final bool isLoggedin = await ApiService.hasUserLoggedIn().timeout(
    const Duration(seconds: 7),
    onTimeout: () => true,
  );
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]).then(
    (val) => runApp(
      PopScope(
        canPop: !kIsWeb,
        child: ProviderScope(child: MyApp(isLoggedin: isLoggedin)),
      ),
    ),
  );
}

/// NOTE: Platform messages are asynchronous,
///  so we initialize in an async method.
@pragma('vm:entry-point')
void backgroundNotificationListener(Map<String, dynamic> data) {
  // Print notification payload data
  print('Received notification: $data');

  // Notification title
  String notificationTitle = 'Message';

  // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
  String notificationText = data['message'] ?? 'Hello World!';

  // Android: Displays a system notification
  // iOS: Displays an alert dialog
  Pushy.notify(notificationTitle, notificationText, data);

  // Clear iOS app badge number
  Pushy.clearBadge();
}

class MyApp extends StatefulWidget {
  const MyApp({
    super.key,
    required this.isLoggedin,
  });

  final bool isLoggedin;

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late GoRouter _router;
  @override
  void initState() {
    super.initState();
      initPlatformState();
    _router = router(widget.isLoggedin);
  }

  // Platform messages are asynchronous, so we initialize in an async method
  Future<void> initPlatformState() async {
    // Start the Pushy service
    Pushy.listen();

    // Set Pushy app ID (required for Web Push)
    Pushy.setAppId('6674bf2b44f72bc8361c971d');

    try {
      // Register the device for push notifications
      String deviceToken = await Pushy.register();

      // Print token to console/logcat
      print('Device token: $deviceToken');

      // Send the token to your backend server
      // ...

      // Update UI with token
      setState(() {});
    } catch (error) {
      // Print to console/logcat
      print('Error: ${error.toString()}');

      // Show error
      setState(() {});
    }

    // Enable in-app notification banners (iOS 10+)
    Pushy.toggleInAppBanner(false);

    // Listen for push notifications received
    Pushy.setNotificationListener(backgroundNotificationListener);

    // Listen for push notification clicked
    Pushy.setNotificationClickListener((Map<String, dynamic> data) {
      // Print notification payload data
      print('Notification clicked: $data');

      // Extract notification messsage
      String message = data['message'] ?? 'Hello World!';

      // Display an alert with the "message" payload value
      showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
              title: Text('Notification clicked'),
              content: Text(message),
              actions: [
                ElevatedButton(
                  child: Text('OK'),
                  onPressed: () {
                    Navigator.of(context, rootNavigator: true).pop('dialog');
                  },
                )
              ]);
        },
      );

      // Clear iOS app badge number
      Pushy.clearBadge();
    });
  }

  @override
  Widget build(BuildContext context) {
  
    return MaterialApp.router(
      routerConfig: _router,
      debugShowCheckedModeBanner: false,
      darkTheme: MythemeModes.darkTheme,
      themeMode: ThemeMode.system,
      title: 'Spark',
      theme: MythemeModes.lightTheme,
    );
  }
}

**Comment by pushy** [comment]
Hi @xanderelsmith,
Thanks for reaching out. We'd be glad to assist with your inquiry.

The Pushy Flutter SDK already supports this out-of-the-box using Flutter background isolates, however, it is essential that you follow our docs closely to position the `backgroundNotificationListener` method in the right place.

Make sure to add the following method to your `main.dart` file, **right after the `import` statements**, and **outside any `Widget` class declaration**, to process push notifications in the background via a Flutter background isolate:
```
// Please place this code in main.dart,
// After the import statements, and outside any Widget class (top-level)

@pragma('vm:entry-point')
void backgroundNotificationListener(Map<String, dynamic> data) {
    // Print notification payload data
    print('Received notification: $data');

    // Notification title
    String notificationTitle = 'MyApp';

    // Attempt to extract the "message" property from the payload: {"message":"Hello World!"}
    String notificationText = data['message'] ?? 'Hello World!';

    // Android: Displays a system notification
    // iOS: Displays an alert dialog
    Pushy.notify(notificationTitle, notificationText, data);

    // Clear iOS app badge number
    Pushy.clearBadge();
}
```

Call the `Pushy.setNotificationListener(backgroundNotificationListener)` method after `Pushy.listen()` to configure the background notification listener:

```
// Listen for push notifications received
Pushy.setNotificationListener(backgroundNotificationListener);
```

Please give it a try, and let us know if there's anything else we can help with.

**Comment by evan8133** [comment]
I have the exact issue with flutter only on android once i killed the app it wont get any notification till i lunch the app again 


```
void initPushy(BuildContext context) async {
  await initNotification();

  // IMPORTANT: Set up notification click handlers
  await messageOpenedHandler();
  log('Notification click handlers initialized', name: 'Pushy');

  // Start the Pushy service
  Pushy.listen();
  Pushy.setNotificationListener(backgroundNotificationListener);
  Pushy.toggleMethodSwizzling(false);
  // Pushy.setNotificationListener((data) async {
  //   // Ensure all Pushy notifications use our custom sound
  //   final notificationData = Map<String, dynamic>.from(data);

  //   // Add sound metadata if not present
  //   if (!notificationData.containsKey('sound')) {
  //     notificationData['sound'] = 'ride_request.mp3';
  //   }

  //   backgroundNotificationListener(notificationData);
  // });

  // Set Pushy app ID (required for Web Push)
  Pushy.setAppId('68e2452***********');

  try {
    log('Initializing Pushy', name: 'Pushy');

    if (Platform.isIOS) Pushy.toggleForegroundService(false);

    // Register the device for push notifications
    String deviceToken = await Pushy.register();
    if (context.mounted) {
      AuthenticationProvider.call(context).setPushyDeviceToken(deviceToken);
    }

    // Print token to console/logcat
    log('Device token: $deviceToken', name: 'Pushy');
  } catch (error, stackTrace) {
    errorHandler(error, stackTrace);
  }

  // Enable in-app notification banners (iOS 10+)
  Pushy.toggleInAppBanner(true);
}
```

```
@pragma('vm:entry-point')
void backgroundNotificationListener(Map<String, dynamic> data) {
  // Print notification payload data
  log('Received notification: $data');
  final notification = NotificationInstance(
    id: int.tryParse('${data['notificationId']}'),
    title: data['notificationTitle'],
    body: data['notificationBody'],
    imageUrl: data['notificationImage'],
    data: data,
  );

  if (notification.id == null &&
      notification.title == null &&
      notification.body == null &&
      notification.imageUrl == null) {
    return;
  }

  showNotification(notification);
  return;
}
```
